<?php

/**
 * @file
 * ACLIB Ref DB module
 */

function aclib_refdb_views_data_alter(array &$data) {
  $data['aclib_refdb_logs']['computed'] = [
    'title' => t('Count access records'),
    'help' => t('A sum of records for various Ref DB fields.'),
    'field' => [
      // ID of the field handler to use - \Drupal\aclib_refdb\Entity\AclibRefdbLogs
      'id' => 'aclib_refdb_computed_field',
    ],
  ];
}