<?php

/**
 * @file
 * ACLIB Ref DB module.
 */

// Uncomment this to add our table available for "Content" based View.
/**
 * Implements hook_views_data_alter().
 *
 * Add our table as a relationship to node_field_data base table.
 */
/*
function aclib_refdb_views_data_alter(array &$data) {
$data['node_field_data']['aclib_refdb_logs']['relationship'] = [
'id' => 'aclib_refdb_logs',
'title' => t('ACLIB RefDb logs'),
'label' => t('ACLIB RefDb logs'),
'group' => t('ACLIB'),
'help' => t('Create a relationship from Content to ACLIB RefDb logs'),
'base' => 'aclib_refdb_logs',
'entity_type' => 'aclib_refdb_logs',
'base field' => 'nid',
'field' => 'nid',
'id' => 'standard',
];
}
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
/*
function aclib_refdb_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  // Hide reset button on ACLIB RefDb report view (/admin/reports/aclib-refdb).
  if ($form['#id'] == 'views-exposed-form-aclib-ref-db-page-1') {
    unset($form['actions']['reset']);
  }
}
*/
