# Main config object
aclib_communico.settings:
  type: config_object
  label: 'Communico API related data'
  mapping:
    communico_api:
      type: mapping
      label: 'Communico API credentials'
      mapping: 
        access_key:
          type: string
          label: 'API access key'
        secret_key:
          type: string
          label: 'API secret key'
        token_endpoint:
          type: string
          label: 'Token endpoint'
        types_endpoint:
          type: string
          label: 'Event types endpoint'
        events_endpoint:
          type: string
          label: 'Events endpoint'
        startDate:
          type: string
          label: 'Start date'
        endDate:
          type: string
          label: 'End date'
        types:
          type: sequence
          label: 'Event types'
          sequence:
            type: string
        limit:
          type: integer
          label: 'Request limit param'
    guzzle_options:
      tyoe: mapping
      label: 'Guzzle options'
      mapping: 
        base_uri:
          type: string
          label: 'API base URI'
        timeout:
          type: integer
          label: 'API timeout setting'
    nodes:
      tyoe: mapping
      label: 'Communico events nodes'
      mapping: 
        node_type:
          type: string
          label: 'Node type'
        node_author:
          type: integer
          label: 'Node author'
        update:
          type: integer
          label: 'Update existing nodes'
        unpublish:
          type: integer
          label: 'Unpublished deleted nodes'
    debug:
      type: integer
      label: 'Debug'