# Main config object
aclib_communico.settings:
  type: config_object
  label: 'MailChimp related data'
  mapping:  &aclib_communico_fields_hash_alias
    communico_api:
      type: mapping
      label: 'Communico API credentials'
      mapping: 
        access_key:
          type: string
          label: 'API access key'
        secret_key:
          type: string
          label: 'API secret key'
        token_endpoint:
          type: string
          label: 'Token endpoint'
        types_endpoint:
          type: string
          label: 'Event types endpoint'
        events_endpoint:
          type: string
          label: 'Events endpoint'
        startDate:
          type: string
          label: 'Start date'
        endDate:
          type: string
          label: 'End date'
        types:
          type: sequence
          label: 'Event types'
          sequence:
            type: string
        limit:
          type: integer
          label: 'Request limit param'
    guzzle_options:
      tyoe: mapping
      label: 'Guzzle options'
      mapping: 
        base_uri:
          type: string
          label: 'API base URI'
        timeout:
          type: integer
          label: 'API timeout setting'
    debug:
      type: integer
      label: 'Debug'

# Field related schema
field.storage_settings.aclib_communico_fields_hash:
  label: 'Aclib communico fields hash'
  type: mapping

field.field_settings.aclib_communico_fields_hash:
  label: 'Aclib communico fields hash'
  type: mapping

field.value.aclib_communico_fields_hash:
  type: mapping
  label: 'Default value'
  mapping: *aclib_communico_fields_hash_alias