<?php

/**
 * @file
 * Provides Communico API integration.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_cron().
 *
 * Queues events from Communico via its API for auto generating appropriate nodes in our Drupal
 */
function aclib_communico_cron() {


  $config = \Drupal::config('aclib_communico.settings'); 
  $guzzle_options = $config->get('guzzle_options');

  if ($config->get('access_key') && $config->get('secret_key') && $config->get('events_endpoint') && !empty($guzzle_options['base_uri'])) { // We do not want anything to run if credentials were not stored in configuration

    // Define our QueueWorker plugin
    $queue = \Drupal::service('queue')->get('aclib_communico_queue');
  
    // Base options for guzzle http request
    $options = [
      'query' => [
        'status' => 'published',
        'limit' => $config->get('limit') ? $config->get('limit') : 100, 
      ]
    ];
 
    // Filter by event types
    if (is_array($config->get('types')) && !empty($config->get('types'))) {
      $types = [];
      foreach ($config->get('types') as $type_key => $type) {
        $types[$type_key] = Html::escape($type); // Do we want this actually? How does Communico APi works with event types names which include "&" in the string and yes, we do have it, also "/" etc.
      }
      $options['query']['types'] = implode(',', $types);
    }

    // Filter by start and end dates
    if ($config->get('startDate')) {
      $options['query']['startDate'] = $config->get('startDate');
    }
    if ($config->get('endDate')) {
      $options['query']['endDate'] = $config->get('endDate');
    }

    // Run our httop request to Communico API
    if ($response = \Drupal::service('aclib_communico.client')->get($config->get('events_endpoint'), $options)) {

      // Pack retrieved data into associative array ready for Node::create
      if (isset($response['data']) && isset($response['data']['entries']) && !empty($response['data']['entries'])) {
        if ($config->get('debug')) {
          \Drupal::logger('ac_credentials')->notice('Debugging mode on - all queued items will be deleted from cron queue. Note that depending of limit number, if high,  it may require a few rounds of cron run.');
          
        }
        foreach ($response['data']['entries'] as $entry) {
    
          // For debuging purposes we atart all over - make sure any possible remaining items in queue are deleted
          if ($config->get('debug')) {
             $queue->deleteItem($entry);
          }
          // Else create each item in the queue
          else {
            $queue->createItem($entry);
          }
        }
      }
    }
  }
  else {
    // Warn user if no credentials set
    \Drupal::logger('ac_credentials')->warning('Aclib communico module enabled but no credentials set on its configuration page.');
  }
}