# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.4
    disk: 2048
    configuration:
      schemas:
        - mysql
        - drupal7
      endpoints:
        admin:
          default_schema: mysql
          privileges:
            mysql: admin
            drupal7: admin
cache:
    type: redis:6.0
