# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.4
    disk: 4096
    configuration:
      schemas:
        - main
        - drupal7
      endpoints:
        mysql:
          default_schema: main
          privileges:
            main: admin
            drupal7: admin
cache:
    type: redis:6.0
